USE UrbanScout;

-- Drop in reverse dependency order
DROP TABLE IF EXISTS Departure_times;
DROP TABLE IF EXISTS Arrival_times;
DROP TABLE IF EXISTS Stops_At;
DROP TABLE IF EXISTS Serves;
DROP TABLE IF EXISTS Services;
DROP TABLE IF EXISTS Verifies;
DROP TABLE IF EXISTS Views;
DROP TABLE IF EXISTS Subscribes_to;
DROP TABLE IF EXISTS `References`;
DROP TABLE IF EXISTS ItineraryItem;
DROP TABLE IF EXISTS Itinerary;
DROP TABLE IF EXISTS IncidentReport;
DROP TABLE IF EXISTS SafetyAlert;
DROP TABLE IF EXISTS NewsPost;
DROP TABLE IF EXISTS Bus;
DROP TABLE IF EXISTS Train;
DROP TABLE IF EXISTS PublicTransit;
DROP TABLE IF EXISTS TransitRoute;
DROP TABLE IF EXISTS TransitStation;
DROP TABLE IF EXISTS Eatery;
DROP TABLE IF EXISTS Landmark;
DROP TABLE IF EXISTS Place;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS User;

-- DROP DATABASE IF EXISTS UrbanScout;
